### ISSUE TITLE
Most currencies in the drop down menu aren't working

### ISSUE THREAD

**Issue by magpie17** [navcoin/navcoin-core#594]
### Description
In the 4.7.0 release candidate (tested on OSX) only the original currencies of NAV, BTC, EUR and USD populate correctly. The other currencies beginning from ARS all show 0.00000 amounts in Balances, Staking and Transactions.

### Motivation
Having the above fields populated with the proper amounts gives users more confidence that the wallet is working correctly.

![Screenshot at Aug 27 23-28-35](https://user-images.githubusercontent.com/50758798/63775339-775a7a00-c922-11e9-8aa4-6b7f8a25f50c.png)

### Acceptance Criteria

Add any additional acceptance criteria you think should be included to the list below.

- [ ] Description is satisfied.
- [ ] Changes display correctly on desktop / mobile.
- [ ] Translations have been added or ammended as necessary.

**Comment by mxaddict** [comment]
@magpie17 this sometimes happens when a price query to the API does not successfully return the values.

It should fix itself once the prices are updated (Once every 5 minutes)

**Comment by magpie17** [comment]
@mxaddict just for added detail, I have clicked on "Update exchange prices" and also quit the navcoin-core wallet and restarted and I still see the same issue with all currencies other than the first 5 in the drop down menu returning 0 values. This hasn't changed (for me) in the 2 days since logging this issue.

**Comment by mxaddict** [comment]
> @mxaddict just for added detail, I have clicked on "Update exchange prices" and also quit the navcoin-core wallet and restarted and I still see the same issue with all currencies other than the first 5 in the drop down menu returning 0 values. This hasn't changed (for me) in the 2 days since logging this issue.

I see, are you running on OSX not windows? Cause we had a similar issue to this on windows, but worked fine on OSX and LINUX

**Comment by mxaddict** [comment]
If possible, can you copy the error log? You should be able to access it from: `Help->Debug Window->Error Log`

**Comment by magpie17** [comment]
Yes I am running this on OSX (version 10.13.6 High Sierra on a Mac Mini Late 2012 just in case the hardware setup is a factor). The Error log is spitting out these error messages every 5 minutes: 2019-08-29 10:15:17 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
2019-08-29 10:20:22 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
2019-08-29 10:25:28 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
2019-08-29 10:30:15 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
2019-08-29 10:35:18 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
2019-08-29 10:40:15 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'

**Comment by mxaddict** [comment]
> Yes I am running this on OSX (version 10.13.6 High Sierra on a Mac Mini Late 2012 just in case the hardware setup is a factor). The Error log is spitting out these error messages every 5 minutes: 2019-08-29 10:15:17 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
> 2019-08-29 10:20:22 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
> 2019-08-29 10:25:28 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
> 2019-08-29 10:30:15 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
> 2019-08-29 10:35:18 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
> 2019-08-29 10:40:15 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'

Thanks, they look like the same issue that the windows builds had.

**Comment by aguycalled** [comment]
@magpie17 could you please provide an address to receive a bounty for reporting this issue?

**Comment by aguycalled** [comment]
i can't see the issue on macos 14.14.4 devnet
<img width="240" alt="image" src="https://user-images.githubusercontent.com/24814046/63970587-d5af6600-caa4-11e9-86cb-5495f6d6924f.png">
<img width="220" alt="image" src="https://user-images.githubusercontent.com/24814046/63970596-da741a00-caa4-11e9-9555-0e6b1a5dbb19.png">
<img width="214" alt="image" src="https://user-images.githubusercontent.com/24814046/63970602-df38ce00-caa4-11e9-9ac2-025ecaa5b8d1.png">
<img width="220" alt="image" src="https://user-images.githubusercontent.com/24814046/63970613-e4961880-caa4-11e9-8ad2-49cf7e359f28.png">
<img width="210" alt="image" src="https://user-images.githubusercontent.com/24814046/63970626-ec55bd00-caa4-11e9-81d8-86fd627b708e.png">

error.log
```
2019-08-29 19:33:32 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
2019-08-29 19:33:42 ERROR: Read: Failed to open file /Users/alex/Library/Application Support/NavCoin4/devnet/peers.dat
2019-08-29 19:33:42 ERROR: Read: Failed to open file /Users/alex/Library/Application Support/NavCoin4/devnet/banlist.dat
```

**Comment by magpie17** [comment]
@aguycalled Thanks, you can send it to NZB1D88gReSbVWp54JZEqCiQS78unCQTcz

**Comment by aguycalled** [comment]
Paid eaa557c6c929d47dd66c0152f9f4c0481cb412583ae8ef14b54789ade899a15c

**Comment by mxaddict** [comment]
@magpie17  @aguycalled  I was able to replicate this issue on OSX 10.14 as well as Windows 10 64 bit

And have created a patch for the issue in #601

**Comment by magpie17** [comment]
tested the new build that @mxaddict created to fix this but I'm seeing the same behaviour and same error messages:                                                                                                                      

![Screenshot at Sep 08 18-55-29](https://user-images.githubusercontent.com/50758798/64486062-caf68d00-d26b-11e9-9198-db9bd50de11d.png)

2019-09-08 08:49:02 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
2019-09-08 08:54:02 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
2019-09-08 08:59:02 ERROR: Could not parse price data json 'boost::property_tree::json_parser::json_parser_error'
